version: "3.4"

services:
  frontend:
    image: registry.heroku.com/xindar/web:latest
    environment:
      PORT: 3000
    ports:
      - "3000:3000"

  backend:
    image: registry.heroku.com/xindar-be/web:latest
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/student
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres:
    name: tutorial_postgres